name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.4'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Set up database
      run: |
        sudo apt-get install -y postgresql-client
        cp config/database.yml.example config/database.yml
        bundle exec rails db:create db:migrate RAILS_ENV=test

    - name: Run tests
      run: |
        bundle exec rspec
